package com.marijana.library1223.enums;

public enum StudentClassEnum {
    ONDERBOUW_GROEP_0,
    ONDERBOUW_GROEP_1,
    ONDERBOUW_GROEP_2,
    MIDDENBOUW_GROEP_3,
    MIDDENBOUW_GROEP_4,
    MIDDENBOUW_GROEP_5,
    BOVENBOUW_GROEP_6,
    BOVENBOUW_GROEP_7,
    BOVENBOUW_GROEP_8;

}
